name: Flutter Web CI/CD

on:
  push:
    branches:
      - main  # Change if your default branch is different

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'  # You can pin a specific version

      # 3. Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 4. Build the web app
      - name: Build Flutter web
        run: flutter build web --release

      # 5. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web

